is_repertoire: True
paired: False
separator: "\t"
columns_to_load: null # OLGA columns are assumed to correspond to: sequences, sequence_aas, v_genes, j_genes
column_mapping: null
region_type: "IMGT_CDR3" # which region to use - IMGT_CDR3 option means removing first and last amino acid as OLGA uses IMGT junction as CDR3
import_empty_nt_sequences: True # keep sequences even though the nucleotide sequence might be empty
import_empty_aa_sequences: False # filter out sequences if they don't have sequence_aa set
import_illegal_characters: False
