# parameters set here are default parameters from the Davidsen et al. 2019 implementation for the basic model
locus: null
beta: 0.75
latent_dim: 20
linear_nodes_count: 75
num_epochs: 5000
batch_size: 10000
pretrains: 10
warmup_epochs: 20
patience: 20
iter_count_prob_estimation: 5
device: cpu
learning_rate: 0.001
cdr3_embed_dim: null
j_gene_embed_dim: null
v_gene_embed_dim: null
seed: null
