import_productive: True
import_with_stop_codon: False
import_out_of_frame: False
region_definition: "IMGT" # which CDR3 definition to use - IMGT option means removing first and last amino acid as Adaptive uses IMGT junction as CDR3
separator: "\t"
columns_to_load: [rearrangement, v_family, v_gene, v_allele, j_family, j_gene, j_allele, amino_acid, templates, frame_type]
column_mapping: # adaptive column names -> immuneML repertoire fields
  rearrangement: sequences # 'rearrangement' is the adaptive name, which will be mapped to 'sequences' in immuneML
  amino_acid: sequence_aas
  v_gene: v_genes
  j_gene: j_genes
  frame_type: frame_types
  v_family: v_subgroups
  j_family: j_subgroups
  v_allele: v_alleles
  j_allele: j_alleles
  templates: counts