is_repertoire: True
path: ./
paired: False
region_type: "IMGT_CDR3" # which region to use - IMGT_CDR3 option means removing first and last amino acid as MiXCR uses IMGT junction as CDR3
separator: "\t"
columns_to_load: [cloneCount, allVHitsWithScore, allJHitsWithScore, aaSeqCDR3, nSeqCDR3]
column_mapping: # MiXCR column name -> immuneML repertoire field (where there is no 1-1 mapping, those are omitted here and handled in the code)
  cloneCount: counts
  allVHitsWithScore: v_genes
  allJHitsWithScore: j_genes
import_empty_nt_sequences: True # keep sequences even though the nucleotide sequence might be empty
import_empty_aa_sequences: False # filter out sequences if they don't have sequence_aa set
import_illegal_characters: False
